data:
  train:
    dataset:
      class_names:
      - class_id
      aug_cfgs:
      - conf/reverb_noise_aug.yaml
      - conf/speed_perturbation_aug.yaml
      return_segment_info:
      - class_id
    sampler:
      sampler_type: seg_chunk_sampler
      min_batch_size: 64
      max_chunk_length: 3.0
      min_chunk_length: 3.0
    data_loader:
      num_workers: 8
  val:
    dataset:
      class_names:
      - class_id
      aug_cfgs:
      - conf/reverb_noise_aug.yaml
      - conf/speed_perturbation_aug.yaml
      return_segment_info:
      - class_id
    sampler:
      sampler_type: seg_chunk_sampler
      min_batch_size: 64
      max_chunk_length: 3.0
      min_chunk_length: 3.0
    data_loader:
      num_workers: 8
feats: fbank80_specaug1_stmn_16k.yaml
model:
  resnet_type: fwseres2net50
  in_channels: 1
  in_feats: 80
  in_kernel_size: 5
  in_stride: 1
  no_maxpool: true
  res2net_width_factor: 3.25
  res2net_scale: 8
  se_r: 4
  pool_net:
    pool_type: ch-wise-att-mean+stddev
    inner_feats: 128
  embed_dim: 192
  loss_type: subcenter-arc-softmax
  num_subcenters: 2
  cos_scale: 30.0
  margin: 0.0
  intertop_margin: 0.0
  margin_warmup_epochs: 3.0
  dropout_rate: 0.0
  norm_before: false
  hid_act: swish
trainer:
  optim: 
    opt_type: adam
    lr: 0.01
    amsgrad: true
    beta1: 0.9
    beta2: 0.95
    weight_decay: 2.0e-05
  lrsched:
    lrsch_type: exp_lr
    decay_rate: 0.5
    decay_steps: 40000
    hold_steps: 65000
    warmup_steps: 15000
    min_lr: 1.0e-06
    update_lr_on_opt_step: true
  use_amp: true
  swa_start: 12
  swa_lr: 1e-5
  swa_anneal_epochs: 2
  log_interval: 1000
  epochs: 20
  eff_batch_size: 256